### ISSUE TITLE
How do I change the look of the display and a few requests

### ISSUE THREAD

**Issue by whiteeagle1985** [Fexcraft/FSMM#14]
Hey,

How do I change the look of the displayed value of your money? Right now it shows the currency as 100.00S$ when I would prefer to have it as S$100.00.

Other than that, I love the way this mod is. Nice way to give new players some money automatically when they enter the world and only an admin can place a new ATM (as it doesn't have a crafting recipe for survival). Thanks for creating such a wonderful mod!

I do have a suggestion: A way to make a shop (or even a cash register for shops) would be welcome, and a way for people to earn money when they exchange items for money (the exchanged items would be available for pickup by the owner of said block or could be removed via hopper or cable).

Thanks again for this wonderful mod!

**Comment by Fexcraft** [comment]
The currency sign can be changed in config, although it's always at end, I might see about a setting for that.

The states mod has a simple "sign shop", but generally there are no standalone/dedicated shop mods yet.
(I know Oxygen API has FSMM support and they offer some kind of shop, but I never checked myself into detail how it works.)

I aren't sure if I understand the "exchange" matter :thinking:

**Comment by whiteeagle1985** [comment]
For the exchange idea, it would be a block where the purchaser would put what blocks they want to buy and how much per block. Sellers would put in blocks that they want to sell, and would receive the amount of money the blocks they put in were worth according to the purchaser's settings in the block. A concept like this is in the Good Ol' Currency mod.

**Comment by andrewminer** [comment]
@whiteeagle1985 — Oxygen provides most of what you're talking about.  I recommend checking it out.  It integrates with FSSM, so you can still use it for your bank/currency.
