### ISSUE TITLE
Add ability to use 3rd-party currency objects

### ISSUE THREAD

**Issue by andrewminer** [Fexcraft/FSMM#15]
I'm creating a modpack which uses Thermal Expansion (TE) very heavily.  I'd love to be able to use the TE coins in place of the notes provided by FSMM (fits the theme of the modpack better).

I've been able to register the TE coins as `ExternalItems` in the config file, but that only gets me the *deposit* side of things.  To handle the *withdrawal* side, I'd love to be able to configure which items get returned for each denomination.  It might even be possible to simplify the config file to:

```
{
    "Currency": [
        {
            "id": "thermalfoundation:coin", "meta": 64, "worth": 1  // copper coin
        }, {
            "id": "thermalfoundation:coin", "meta": 69, "worth": 10  // silver coin
        }, {
            "id": "thermalfoundation:coin", "meta": 1,  "worth": 100  // gold coin
        }, {
            "id": "thermalfoundation:coin", "meta": 70, "worth": 1000  // platinum coin
        }, {
            "id": "thermalfoundation:coin", "meta": 70, "worth": 10000  // enderium coin
        }, {
            "id": "thermalfoundation:coin", "meta": 71, "worth": 100000  // iridium coin
        }
    ],
    "Banks": {
        // as is...
    }
}
```

The default, of course, would use all the FSMM items as currency, but modpack authors would have the freedom to substitute any other items they like.

**Comment by Fexcraft** [comment]
:thinking: There should be a "register" keyword, I'll check later on correct placement of it.

**Comment by andrewminer** [comment]
Oh!  If that what that does, then I can just delete the ‘Items’ section so it *only* uses the external items?

**Comment by Fexcraft** [comment]
The intended usage of the config is to add own "internal" items that FSMM can `generate` (but a modpack has to add textures themselves) or to remove (all) internal items.
The external items then can be regarded as valid money to count and consume, but only the registered ones will pay out of the ATM.
(IIRC)

**Comment by andrewminer** [comment]
Removing the `Items` section entirely did exactly what I wanted.  🥇
