### ISSUE TITLE
ATM/Bank eats money

### ISSUE THREAD

**Issue by AzazelMango** [Fexcraft/FSMM#16]
So I have my own currency and I was depositing some of it when I noticed it not counting the sterling (cent value). I removed 0.01D and added it back. The resulting balance was 811.00D to 810.00D. I believe this may be a bug due to me not being able to find a place in the config files to prevent this from occuring.
Thanks!

**Comment by Fexcraft** [comment]
Could you send the `.json` with the custom currency items configured?

**Comment by AzazelMango** [comment]
https://www.dropbox.com/s/zmbhv5nzi260mfh/configuration.json?dl=0
https://www.dropbox.com/s/w7wxdpghunpiar2/config.cfg?dl=0

I double checked and I still dont know what happened.

**Comment by Fexcraft** [comment]
Did it print anything into chat?
Did you input using the buttons or the amount field?

The button input assumes always you take centesimals into account too.

**Comment by AzazelMango** [comment]
I made sure to use the centecimals but it still doesnt add it into the amount. I used the /money command to be sure I had the correct amount. I.e. 1426.45D to 1426.450D.

**Comment by Fexcraft** [comment]
🤔
I'll have to check this later, as I don't have those items I have to setup something locally.

**Comment by AzazelMango** [comment]
I can send you the mod if you wish. And thanks again for the help

**Comment by Fexcraft** [comment]
If you want you can.

**Comment by AzazelMango** [comment]
https://www.dropbox.com/s/begatmf3e3t3s2o/sr_essentials-1.1.1.jar?dl=0

**Comment by Fexcraft** [comment]
that's how the ``configuration.json`` works on my client
https://youtu.be/qvf0ChBL-ds

**Comment by AzazelMango** [comment]
Thats very strange. I think I should also have mentioned that it is used on a server. But I dont see why it doesnt work that way even tho I am using it the same way

**Comment by Fexcraft** [comment]
I can try that on a test server later too.
Are you sure the config looks the same on both server and client?
Specifially server side is important to have the correct file.

**Comment by AzazelMango** [comment]
After some thought it may be conflicting with oxygen bacause it also doesnt support the cents.

**Comment by Fexcraft** [comment]
Hmm, it could be, I personally never used Oxygen to know.

**Comment by AzazelMango** [comment]
I will talk to the devs for oxygen about it too but, I also have another question regarding the custom currency. Is there a way to make the name of it different from foney?

**Comment by Fexcraft** [comment]
Is the name hardcoded anywhere?

Only the default ones are called "foney" (which you disabled in your configuration).
And their display name ingame can be changed by modifying the .lang file entries.

Also as far I recall by defining custom entries in "Items" part of the configuration,
FSMM will create custom items with that name (but under the fsmm domain).
But those will NOT also have assets generated (item icon, json, lang),
you'd need to create them yourself, I'd suggest a resourcepack.
(a resourcepack wouldn't need to modify the mod jar)

EDIT:
https://github.com/AustereTony-MCMods/Oxygen-Core/issues/22
Maybe.. that's also related to Oxygen.
