### ISSUE TITLE
FSMM doesn't recognize any currency including its own

### ISSUE THREAD

**Issue by MrTitainin** [Fexcraft/FSMM#17]
I'm playing on custom modpack, singleplayer, occasionally switching to LAN. I downloaded FSMM 2.4.0 and tried it, but no matter what the settings are it doesn't let me deposit money and value doesn't appear in tooltip. Withdrawal works correctly though.

This part of log might be related:
[20:29:35] [Client thread/WARN]: Unable to inject capability net.fexcraft.mod.fsmm.api.MoneyCapability at net.fexcraft.mod.fsmm.impl.cap.MoneyCapabilityUtil.instance (Non-Static)
[20:29:35] [Client thread/WARN]: Unable to inject capability net.fexcraft.mod.fsmm.api.PlayerCapability at net.fexcraft.mod.fsmm.impl.cap.PlayerCapabilityUtil.instance (Non-Static)

If you need modlist, screenshot or something I can provide those too.

**Comment by Fexcraft** [comment]
Please try this FSMM jar, includes the edits from the last 2 commits.
https://cdn.discordapp.com/attachments/424351061873131521/844651226573832192/FSMM-2.4.0b-1.12.x.jar
(It was uploaded using Discord.)

**Comment by MrTitainin** [comment]
No difference. Does it work for you?

**Comment by Fexcraft** [comment]
The jar I sent should have fixed the warning from your first message.
For me personally it works, I tested it yesterday in a dev client too.
It could be an issue related to another mod though, I'd need more info like a log or so.

**Comment by MrTitainin** [comment]
[Here](https://drive.google.com/file/d/1zw5H-RkwqUqDikocJZ7AhV-agjM3TDt_/view?usp=sharing)'s the modpack and
[here](https://gist.github.com/MrTitainin/42a08838588c9b7e34c8a59c04624064)'s the latest log which I think was the one I was testing that new version on. It doesn't seem to have that warning message. I removed Galacticraft from modpack I sent you because it's not on curseforge and thus takes a lot of space, but it's usually there, you might need to remove Extra Plantes too. On a side note, you might need to increase RAM to 5-6GB, but it theoretically runs with normal 4GB.

**Comment by Fexcraft** [comment]
Tried the modpack, I think my computer is getting too old for this... the lag and loading time are huge.
Can confirm the tooltip is missing as well as them not working for deposit, sadly I can't really do testing on that myself.

**Comment by MrTitainin** [comment]
Well, the mods are mostly independent from each other so I think you can do testing on smaller batches to identify the conflicting mod (JEI and Ancient Warfare seem to have big impact on loading time). As a side note, it takes about 10min to load on my computer but it doesn't lag if it has about 6GB of RAM. I might try some combinations myself when I have time.

**Comment by MrTitainin** [comment]
After testing several different combinations of mods, getting both broken and working builds, I'm starting to see a pattern - it seems to be a matter of quantity, rather than quality. If number of registered items or something exceeds a certain treshold, your mod stops finding yours on the list when assigning values to them - that's my current theory after seeing various big mods sometimes removing/adding the bug when switched on/off and sometimes not. Perhaps your loop or sth has a fixed limit to it?

**Comment by Fexcraft** [comment]
Well, there's no loop or odd things like that.
It runs purely on forge events, forge capabilities and config.
Since withdraw works, it means the config has loaded correctly.
But the _ItemStack's_ worth and tooltip is usually taken from the Capability,
which since neither work, something is interfering with Capability assignment.

I could make an edit to put into tooltip more info and compile/send that version.

**Comment by Fexcraft** [comment]
_Seems to be fixed via https://github.com/Fexcraft/FSMM/commit/29774744cb06fee421a1aac0b097b110b3e551d7_
