### ISSUE TITLE
Banks

### ISSUE THREAD

**Issue by NicksGameDevelopers** [Fexcraft/FSMM#18]
How do you create new banks in Minecraft

**Comment by Fexcraft** [comment]
Right now there is no GUI to create or manage a bank in-game.
But the ATM GUI allows you to change your account's bank to another bank, if there's more than one.

To create more banks you can add a new entry in `/config/fsmm/configuration.json`.
Alternatively you can do it in `/saves/<your world>/fsmm/banks/`, in that folder are also all existing banks and their data, if you ever need to update any of them.
Please make sure the filename is the same as bank ID if adding banks into the `/saves/<your world/fsmm/banks/` folder.
