### ISSUE TITLE
license for legacy version

### ISSUE THREAD

**Issue by trollogyadherent** [Fexcraft/FSMM#19]
Hello, would it be possible to relicense the 1.7.10 version under MIT or LGPL? I am interested in the mod but don't want to have to deal with the present license, if I work on a fork.

**Comment by Fexcraft** [comment]
No, the 1.7 version only has a creative tab and items. I think you can make an own mod like this fairly easily.

**Comment by trollogyadherent** [comment]
Ok, thanks for the information, I will indeed look at making something suiting my needs. Have a nice day
