### ISSUE TITLE
FSMM for 1.12.2 built against FCL for 1.14/1.17 - Crashes looking for Formatter

### ISSUE THREAD

**Issue by ccrvincent** [Fexcraft/FSMM#22]
Looking at the FCL repo, the Formatter class doesn't exist in the 1.12 branch, only the 1.14 and Fabric 1.17 branches.

Not sure if you want this here to remove the dependency on Formatter, or on the FCL repo to update FCL for 1.12 to have the class.

[crash-2023-12-28_11.45.04-client.txt](https://github.com/Fexcraft/FSMM/files/13789140/crash-2023-12-28_11.45.04-client.txt)

**Comment by Fexcraft** [comment]
Update FSMM, you're using an old version that is imcompatible with latest FCL.
Similarly with FSMM-Shop

**Comment by Fexcraft** [comment]
Issue may be reopened if there's still crashes when all mods are up to date.

**Comment by ccrvincent** [comment]
> Update FSMM, you're using an old version that is imcompatible with latest FCL. Similarly with FSMM-Shop

I was reporting for someone else and I double-checked FCL's version a few times to be sure, but totally missed the outdated FSMM.  Sorry for the inconvenience!
