### ISSUE TITLE
FSMM to Oxygen Market

### ISSUE THREAD

**Issue by WildPandaUa** [Fexcraft/FSMM#25]
How I can connect these two mods? I have to change some configs?

**Comment by Fexcraft** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/oxygen-currency-providers

**Comment by WildPandaUa** [comment]
> https://legacy.curseforge.com/minecraft/mc-mods/oxygen-currency-providers

Thanks, I saw this mod and I have it but, my balance in Oxygen market still 0. Balance in FSMM 500 000. Can you write simple steps how to connect them?)

P.S. I apologize in advance for my English, I hope you 
understand me)

**Comment by Fexcraft** [comment]
It should work automatically when all 3 mods (OxygenAPI, FSMM, Oxygen Currency Provider) are present.
You also have to make sure to download the correct currency provider.
Do you get any errors in log that mention fsmm?

I have not used Oxygen myself, only wrote the currency provider.

**Comment by WildPandaUa** [comment]
Maybe it's because I tried to use Grand economy bridge? I'll try to remove it and try again. Sorry for the stupid questions)

**Comment by WildPandaUa** [comment]
Oxygen API work on 1.12.2?

**Comment by Fexcraft** [comment]
On CurseForge it only exists for 1.12 it seems.

**Comment by WildPandaUa** [comment]
Oh, I'm sorry, I didn't notice that in  Currency Provider there are separate files for each currency. My bad

**Comment by WildPandaUa** [comment]
I did everything as you wrote, but there is still currency in the market from the oxygen(

**Comment by Fexcraft** [comment]
Iirc oxygen did sync the FSMM player account balance with oxygen balance.
It doesn't touch money items in inventory. It also doesn't support decimals, only full number money (so no cents).

Is there any fsmm related errors in log?
It could be the compatibility broke at some update.

**Comment by WildPandaUa** [comment]
way to provider H:\Minecraft\Instances\Minecraft Trillionaire fin v.1.1\config\oxygen\currency providers
provider name fsmm.json
provider text:
{
  "version": "0.11.1:beta:0",
  "server": {
    "provider_index": 0,
    "force_balance_sync": true
  }
}
way to currency H:\Minecraft\Instances\Minecraft Trillionaire fin v.1.1\config\oxygen\data\client\properties\currency
I deleted this folder twice, but it still creates it and use oxygen currency

**Comment by WildPandaUa** [comment]
No errors)

**Comment by WildPandaUa** [comment]
![image](https://github.com/Fexcraft/FSMM/assets/174196463/cf348acb-64eb-4186-b608-9bda6b91f5ff)

**Comment by Fexcraft** [comment]
Hmm. Sadly I don't know.
Try a FSMM and FCL version closer with release date to the currency provider?

**Comment by WildPandaUa** [comment]
FCL?

**Comment by Fexcraft** [comment]
"Fexcraft Common Library"

**Comment by WildPandaUa** [comment]
Ok, I'll try

**Comment by WildPandaUa** [comment]
Thank you, it helped. I have installed older versions. Last provider date 5/20/2020

**Comment by Fexcraft** [comment]
https://curseforge.com/minecraft/mc-mods/oxygen-fsmm-compat
