### ISSUE TITLE
crash and invite expired

### ISSUE THREAD

**Issue by tomq0608** [Fexcraft/FSMM#3]
1. the discord invite has expired
2. I get this crash:
[crash-2018-07-06_19.42.01-client.txt](https://github.com/Fexcraft/FSMM/files/2171624/crash-2018-07-06_19.42.01-client.txt)

**Comment by Fexcraft** [comment]
Which link? The one I checked just now on Github seemed to work.

**Comment by Fexcraft** [comment]
Have you modified the FSMM cofigs, especially the configured items?

**Comment by tomq0608** [comment]
No,
I’m trying to use it on the tekxit mod pack.
On 6 Jul 2018, at 19:56, Fexcraft <notifications@github.com<mailto:notifications@github.com>> wrote:


Have you modified the FSMM cofigs, especially the configured items?

**Comment by Fexcraft** [comment]
FSMM and FCL version?

**Comment by Fexcraft** [comment]
Please try the newest FSMM version (2.1.4).
