### ISSUE TITLE
Crash: Suspected FSMM

### ISSUE THREAD

**Issue by WACriminalG2** [Fexcraft/FSMM#4]
Crash log is here: https://pastebin.com/t9W35p1w

World loaded and ran fine for a few minutes, just flying around in creative mode. Suddenly crashed with this log.

**Comment by Fexcraft** [comment]
Will look into it probably when I'm back...
Definitely an error thrown from the AccountManager saving data.

**Comment by Fexcraft** [comment]
Please try the 2.1.5 version 🤔
