### ISSUE TITLE
Feature request - payday - players get paid x credit for x amount of time on the server.

### ISSUE THREAD

**Issue by ProsperCraft** [Fexcraft/FSMM#5]
See - https://github.com/Flibio/PayDay  for the sponge plugins
 and https://dev.bukkit.org/projects/payday for the bukkit plugin.

It is very helpful for players to earn money for being online, and boosts playercounts for server owners.

And provides a reward for frequent players.

**Comment by Fexcraft** [comment]
It feels more like something that should be in a dedicated mod or function 🤔
FSMM provides money, an ATM block & API, it's "Fex's ***Small*** Money Mod" after all.

Relating to that though, I planned in [States](https://github.com/Fexcraft/States) to have "Companies" and/ore municipality/state employees who would have a set salary.

**Comment by Fexcraft** [comment]
Is this still relevant/wanted?

Also FSMM is Forge Votifier compatible since a while now.
https://www.curseforge.com/minecraft/mc-mods/voting
https://www.curseforge.com/minecraft/mc-mods/fsmm

**Comment by ProsperCraft** [comment]
Yes, still wanted, this has nothing to do with voting, players get paid for being online.

**Comment by Fexcraft** [comment]
I could see for such a thing (as separate mod) eventually when taking a break from dev of the larger mods.
😂 would need a name though.

**Comment by ProsperCraft** [comment]
Your currency is specific to your mod though right? so it wouldn't really benefit anyone else or would it?

**Comment by Fexcraft** [comment]
🤔

**Comment by ProsperCraft** [comment]
I guess if your currency is an item, you could just specify give -configurable- item to player ever -configurable- amount of time.  server owners would gobble that up.

**Comment by Fexcraft** [comment]
Hmm, well, yes. I would give the option to either give items or pay directly into the account, as I did with the votifier compability.

**Comment by Fexcraft** [comment]
https://www.curseforge.com/minecraft/mc-mods/time-pays
https://github.com/Fexcraft/TimePays

If there are any issues with the mod, you can post there.
