### ISSUE TITLE
World information being stored improperly in the config folder.

### ISSUE THREAD

**Issue by ProsperCraft** [Fexcraft/FSMM#6]
It appears that the information about the world, specifically financial information is being stored in the config folder.

A server owner expects all information to be saved in the world folder, this is what typically gets backed up, and when a rollback occurs gets rolled back, now if FSMM stores data in the config folder this is a problem because when the world gets rolled back then it would be out of sync with the financial data.

Another issue with this is when server owners update a modpack, they copy the mods and configs from the updated pack and copy them into the server root replacing the prior mods and configs folders, thereby resetting the balances of all of the players.

Suggested fix- store the financial data in the world folder.

**Comment by Fexcraft** [comment]
🤔 data saving is a matter from pre-States times, saving in the world data wasn't an option back then.
I'll see about changing that in future/next FSMM versions.
